Rockchip: stop build when bootloader copy fails

diff --git a/projects/Rockchip/bootloader/install b/projects/Rockchip/bootloader/install
--- a/projects/Rockchip/bootloader/install
+++ b/projects/Rockchip/bootloader/install
@@ -39,12 +39,12 @@ esac
 if [ -n "$PKG_DATAFILE" -a -n "$PKG_LOADER" ]; then
   tools/mkimage -n $PKG_SOC -T rksd -d "$PKG_DATAFILE" idbloader.img
   cat "$PKG_LOADER" >> idbloader.img
-  cp -av idbloader.img $INSTALL/usr/share/bootloader
+  cp -av idbloader.img $INSTALL/usr/share/bootloader || die "$(print_color CLR_ERROR "ERROR: idbloader.img could not be copied")"
 fi
 
 if [ -n "$PKG_LOAD_ADDR" ]; then
   $PKG_RKBIN/tools/loaderimage --pack --uboot u-boot-dtb.bin uboot.img $PKG_LOAD_ADDR
-  cp -av uboot.img $INSTALL/usr/share/bootloader
+  cp -av uboot.img $INSTALL/usr/share/bootloader || die "$(print_color CLR_ERROR "ERROR: uboot.img could not be copied")"
 fi
 
 if [ -n "$PKG_BL31" ]; then
@@ -63,5 +63,5 @@ SEC=0
 PATH=trust.img
 EOF
   $PKG_RKBIN/tools/trust_merger --verbose trust.ini
-  cp -av trust.img $INSTALL/usr/share/bootloader
+  cp -av trust.img $INSTALL/usr/share/bootloader || die "$(print_color CLR_ERROR "ERROR: trust.img could not be copied")"
 fi
